/**
 * This was generated by GPT-3 prompt:
 * This is a list of 10 example blog posts in JSON format for an example blogging boilerplate website.
 * Each blog post only has "title" and "content" properties. "content" value's string length is  not less than 300 words.
 */
 export default [
    {
      id: 301,
      title: '10 benefits of black garlic',
      tags: ['health', 'food', 'garlic'],
      content:
        'Did you know  that black garlic has 10 benefits? Here they are:\n\n1. Black garlic can improve blood circulation.\n2. It can also help to prevent cancer.\n3. Black garlic can help to improve your immune system.\n4. It can also help to improve your digestion.\n5. Black garlic can help to boost your energy levels.\n6. It can also help to improve your skin health.\n7. Black garlic can help to reduce inflammation.\n8. It can also help to fight depression.\n9. Black garlic can help to improve your cognitive function.\n10. It can also help to reduce stress levels.',
    },
    {
      id: 302,
      title: 'How to make a perfect cup of coffee',
      tags: ['health', 'food', 'coffee'],
      content:
        "There are a few steps to making a perfect cup of coffee. First, you need to start with fresh, cold water. Bring the water to a boil and then let it cool for about 30 seconds before pouring it over the coffee grounds. Use about 2 tablespoons of coffee grounds for every 6 ounces of water.\n\nNext, you'll need to stir the coffee grounds and water together and then let them steep for about 4 minutes. After 4 minutes, remove the coffee grounds by either pouring the coffee through a filter or using a French press.\n\nFinally, enjoy your cup of coffee!",
    },
    {
      id: 303,
      tags: ['eggs', 'breakfast', 'recipe'],
      title: 'How to make a perfect scrambled egg',
      content:
        "There are a few steps to making perfect scrambled eggs. First, you need to whisk the eggs together in a bowl. Then, you'll need to heat up some butter in a pan over medium heat.\n\nOnce the butter is melted, add the eggs to the pan and cook them, stirring frequently, until they are cooked to your liking.\n\nOnce they're cooked, add salt and pepper to taste and serve immediately.",
    },
    {
      id: 304,
      tags: ['sandwich', 'lunch', 'recipe'],
      title: 'How to make a perfect grilled cheese sandwich',
      content:
        "There are a few steps to making a perfect grilled cheese sandwich. First, you'll need to butter the bread on both sides. Then, you'll need to add cheese to one side of the bread and place the other slice of bread on top, butter side up.\n\nNext, you'll need to place the sandwich in a pan over medium heat. Cook the sandwich for about 2 minutes per side, or until the bread is golden brown and the cheese is melted.\n\nFinally, enjoy your grilled cheese sandwich!",
    },
    {
      id: 305,
      tags: ['sandwich', 'lunch', 'recipe'],
      title: 'How to make a perfect PB&J sandwich',
      content:
        "There are a few steps to making a perfect PB&J sandwich. First, you'll need to choose your bread. You can use any type of bread, but white bread is the most classic choice.\n\nNext, you'll need to choose your peanut butter and jelly. You can use any type of peanut butter and jelly, but classic peanut butter and grape jelly are the most classic choice.\n\nOnce you've chosen your bread and peanut butter and jelly, you'll need to spread the peanut butter on one slice of bread and the jelly on the other. Then, you'll need to put the two slices of bread together and enjoy your sandwich!",
    },
    {
      id: 306,
      tags: ['eggs', 'breakfast', 'recipe'],
      title: 'How to make a perfect omelette',
      content:
        "There are a few steps to making a perfect omelette. First, you'll need to whisk the eggs together in a bowl. Then, you'll need to add some butter to a pan and heat it over medium heat.\n\nOnce the butter is melted, add the eggs to the pan and cook them, stirring frequently, until they are cooked to your liking.\n\nOnce they're cooked, add salt and pepper to taste and serve immediately.",
    },
    {
      id: 307,
      tags: ['salad', 'vegetables', 'recipe'],
      title: 'How to make a perfect salad',
      content:
        "There are a few steps to making a perfect salad. First, you'll need to choose your greens. You can use any type of greens, but spinach and kale are the most classic choice.\n\nNext, you'll need to choose your toppings. You can use any type of toppings, but tomatoes, cucumbers, and onions are the most classic choice.\n\nFinally, you'll need to choose your dressing. You can use any type of dressing, but balsamic vinegar and olive oil are the most classic choice.\n\nOnce you've chosen your greens, toppings, and dressing, you'll need to mix them all together and enjoy your salad!",
    },
    {
      id: 308,
      tags: ['smoothie', 'breakfast', 'recipe'],
      title: 'How to make a perfect smoothie',
      content:
        "There are a few steps to making a perfect smoothie. First, you'll need to choose your fruits and vegetables. You can use any type of fruits and vegetables, but bananas, strawberries, and blueberries are the most classic choice.\n\nNext, you'll need to choose your liquid. You can use any type of liquid, but milk and water are the most classic choice.\n\nFinally, you'll need to choose your add-ins. You can use any type of add-ins, but yogurt and honey are the most classic choice.\n\nOnce you've chosen your fruits and vegetables, liquid, and add-ins, you'll need to blend them all together and enjoy your smoothie!",
    },
    {
      id: 309,
      tags: ['chicken', 'lunch', 'recipe'],
      title: 'How to make a perfect grilled chicken',
      content:
        "There are a few steps to making perfect grilled chicken. First, you'll need to marinate the chicken. You can use any type of marinade, but a classic Italian dressing is the most classic choice.\n\nNext, you'll need to grill the chicken. Preheat your grill to medium-high heat and then grill the chicken for about 10 minutes per side, or until it is cooked through.\n\nFinally, enjoy your grilled chicken!",
    },
  ];
  